# Generated by Django 4.1.1 on 2022-10-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BLANK', max_length=150)),
                ('img', models.CharField(default='BLANK', max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='module',
            name='manufacturer',
            field=models.ForeignKey(default='BLANK', on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='main_app.manufacturer'),
        ),
    ]
